global ADDRESS = 0x0

global SCREEN_WIDTH = 100
global SCREEN_HEIGHT = 50

global PIX_WIDTH = 8
global PIX_HEIGHT = 8

global WINDOW_WIDTH = SCREEN_WIDTH * PIX_WIDTH
global WINDOW_HEIGHT = SCREEN_HEIGHT * PIX_HEIGHT

