#!/usr/bin/env python

import sys
from tkinter import * 

import mlv_vars
import mlv_screen
import mlv_debugger

import time

if len(sys.argv) == 2:
  filename = sys.argv[1]

  with open(filename, "rb") as binary_file:
    data = binary_file.read()

    cpu = Cpu()
    cpu.load_in_memory(data)

    cpu.attach(Screen(canvas))
    cpu.attach(Debugger(canvas))
    cpu.run()

    fenetre = Tk()

    label = Label(fenetre, text="My little VM")
    label.pack()

    canvas = Canvas(fenetre, width=WINDOW_WIDTH, height=WINDOW_HEIGHT, background='black')

    canvas.pack()

    fenetre.mainloop()

else
  print("Usage: my_little_vm <rom_name>")
