#!/usr/bin/env python
import sys
from mlv_tkapp import *

if len(sys.argv) == 2:
  filename = sys.argv[1]

  with open(filename, "rb") as binary_file:
    binary = binary_file.read()

    app = TkApp()

    app.load_binary(binary)

    app.mainloop()

else:
  print("Usage: my_little_vm <rom_name>")
